-- This script was generated automatically by pgAdmin
-- However is not strictly necessary since Hibernate generates the scheme once the app is running

BEGIN;

    CREATE TABLE IF NOT EXISTS public.club
    (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
        address character varying(255) COLLATE pg_catalog."default" NOT NULL,
        contact_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
        contact_phone character varying(255) COLLATE pg_catalog."default" NOT NULL,
        created_at timestamp(6) without time zone,
        description character varying(255) COLLATE pg_catalog."default" NOT NULL,
        name character varying(255) COLLATE pg_catalog."default" NOT NULL,
        updated_at timestamp(6) without time zone,
        CONSTRAINT club_pkey PRIMARY KEY (id),
        CONSTRAINT ukshoqrf645n82ifvmd28y4s2os UNIQUE (contact_email, contact_phone)
    );

    CREATE TABLE IF NOT EXISTS public.court
    (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
        court_environment character varying(255) COLLATE pg_catalog."default" NOT NULL,
        created_at timestamp(6) without time zone,
        name character varying(255) COLLATE pg_catalog."default" NOT NULL,
        surface character varying(255) COLLATE pg_catalog."default" NOT NULL,
        updated_at timestamp(6) without time zone,
        club_id integer NOT NULL,
        CONSTRAINT court_pkey PRIMARY KEY (id)
    );

    CREATE TABLE IF NOT EXISTS public.reservation
    (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
        created_at timestamp(6) without time zone,
        reservation_end_time timestamp(6) without time zone NOT NULL,
        reservation_start_time timestamp(6) without time zone NOT NULL,
        status character varying(255) COLLATE pg_catalog."default" NOT NULL,
        updated_at timestamp(6) without time zone,
        court_id integer NOT NULL,
        user_id integer NOT NULL,
        CONSTRAINT reservation_pkey PRIMARY KEY (id)
    );

    CREATE TABLE IF NOT EXISTS public.users
    (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
        contact_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
        contact_phone character varying(255) COLLATE pg_catalog."default",
        created_at timestamp(6) without time zone,
        first_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
        last_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
        password character varying(255) COLLATE pg_catalog."default" NOT NULL,
        role character varying(255) COLLATE pg_catalog."default" NOT NULL,
        updated_at timestamp(6) without time zone,
        club_id integer,
        CONSTRAINT users_pkey PRIMARY KEY (id),
        CONSTRAINT uk3sk50frgdspvn94x3w0uysmii UNIQUE (contact_email),
        CONSTRAINT uknck1mcsb5bmdb9ysei1f6omnl UNIQUE (club_id)
    );

    ALTER TABLE IF EXISTS public.court
        ADD CONSTRAINT fklx9vx4l1e6l0p6jg8el1xfuit FOREIGN KEY (club_id)
        REFERENCES public.club (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


    ALTER TABLE IF EXISTS public.reservation
        ADD CONSTRAINT fkpxnu37u6x3lp9jvebvujghn4e FOREIGN KEY (court_id)
        REFERENCES public.court (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


    ALTER TABLE IF EXISTS public.reservation
        ADD CONSTRAINT fkrea93581tgkq61mdl13hehami FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


    ALTER TABLE IF EXISTS public.users
        ADD CONSTRAINT fk1hmhr0kxtsctapyr0a62ot9m3 FOREIGN KEY (club_id)
        REFERENCES public.club (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
    CREATE INDEX IF NOT EXISTS uknck1mcsb5bmdb9ysei1f6omnl
        ON public.users(club_id);

END;